"""Generic lineage-aware NicheFate facade."""

from .clone_matrix import (
    REQUIRED_JOINT_CLONE_QC_COLUMNS,
    build_joint_clone_assignment,
    build_joint_clone_matrix,
    build_validated_joint_clone_summary,
    compare_joint_clone_layers,
    load_selected_audit_tables,
    select_lineage_freeze_label,
    validate_joint_clone_outputs,
)
from .clone_niche import (
    aggregate_joint_clone_to_units,
    integrate_joint_clones_to_niches,
    load_group_map,
    load_metaniche_cell_map,
    load_tile_map,
)
from .dynamics_interface import freeze_dynamics_interface_design
from .evidence import (
    aggregate_lineage_to_groups,
    build_canonical_lineage_evidence,
    compute_lineage_diversity_metrics,
    h5ad_path_for_lineage_sample,
    load_lineage_allele_annotation,
    load_lineage_cellbin_table,
    load_lineage_evidence,
    load_lineage_h5ad_packet,
    prepare_lineage_packet_root,
    summarize_cellbin_lineage_evidence,
    validate_lineage_h5ad_schema,
)
from .input_contract import (
    ALLELE_ANNOTATION_REQUIRED_COLUMNS,
    CELLBIN_SUMMARY_REQUIRED_FIELDS,
    EXPECTED_ASSAYS,
    GROUP_ASSIGNMENT_OPTIONAL_COLUMNS,
    GROUP_ASSIGNMENT_REQUIRED_COLUMNS,
    LINEAGE_EVIDENCE_REQUIRED_COLUMNS,
    PRIMARY_JOIN_KEY,
    REQUIRED_H5AD_LAYERS,
    REQUIRED_H5AD_OBSM,
    REQUIRED_H5AD_OBS_FIELDS,
    LineageInputContract,
    draft_lineage_input_contract_payload,
    load_lineage_input_contract,
)
from .qc import (
    audit_allele_annotation,
    build_cellbin_assay_qc,
    compare_file_snapshots,
    snapshot_files,
    validate_cellbin_lineage_join,
    verify_manifest,
)
from .visualization import build_lineage_figures

__all__ = [
    "ALLELE_ANNOTATION_REQUIRED_COLUMNS",
    "EXPECTED_ASSAYS",
    "GROUP_ASSIGNMENT_OPTIONAL_COLUMNS",
    "GROUP_ASSIGNMENT_REQUIRED_COLUMNS",
    "LINEAGE_EVIDENCE_REQUIRED_COLUMNS",
    "LineageInputContract",
    "PRIMARY_JOIN_KEY",
    "REQUIRED_H5AD_LAYERS",
    "REQUIRED_H5AD_OBSM",
    "REQUIRED_H5AD_OBS_FIELDS",
    "CELLBIN_SUMMARY_REQUIRED_FIELDS",
    "REQUIRED_JOINT_CLONE_QC_COLUMNS",
    "aggregate_joint_clone_to_units",
    "aggregate_lineage_to_groups",
    "audit_allele_annotation",
    "build_canonical_lineage_evidence",
    "build_cellbin_assay_qc",
    "build_joint_clone_assignment",
    "build_joint_clone_matrix",
    "build_lineage_figures",
    "build_validated_joint_clone_summary",
    "compare_file_snapshots",
    "compare_joint_clone_layers",
    "compute_lineage_diversity_metrics",
    "draft_lineage_input_contract_payload",
    "freeze_dynamics_interface_design",
    "h5ad_path_for_lineage_sample",
    "integrate_joint_clones_to_niches",
    "load_group_map",
    "load_lineage_allele_annotation",
    "load_lineage_cellbin_table",
    "load_lineage_evidence",
    "load_lineage_h5ad_packet",
    "load_lineage_input_contract",
    "load_metaniche_cell_map",
    "load_selected_audit_tables",
    "load_tile_map",
    "prepare_lineage_packet_root",
    "select_lineage_freeze_label",
    "snapshot_files",
    "summarize_cellbin_lineage_evidence",
    "validate_cellbin_lineage_join",
    "validate_lineage_h5ad_schema",
    "validate_joint_clone_outputs",
    "verify_manifest",
]
